### ISSUE TITLE
Authorizations end point returning error 404

### ISSUE THREAD

**Issue by kenpachiii** [pokitdok/pokitdok-python#34]
When making a request to `pd.authorizations` I get 

`{'closest_api_match': ['/api/v4/authorizations/'],
 'error': '404. Endpoint not found',
 'requested_endpoint': '/api/v4/authorizations/'}`

Any insights towards why I would be getting this?

**Comment by corbinbs** [comment]
Hi @kenpachiii 

Unfortunately you've stumbled upon some code in the pokitdok-python library that should have been removed a long time ago.   I'm very sorry for that causing confusion.  The PokitDok Platform did offer authorizations and referrals APIs at one point that would enable folks to easily sling the equivalent of X12 278 data to trading partners that supported those transactions.   However, the overall experience of those APIs was not up to par with the other X12 APIs.  Part of that was due to how those transactions were implemented (or not implemented at all) with various partners.   It may be that those APIs make a return at some point in the future once more partners have good overall support for those (including providing the necessary supporting information for them).  For most of the customers initially using these APIs, making the API call and then still having to mail, FAX, or ship 📨 around wasn't a good developer / user experience.   For that reason, they were deactivated on the platform until they can return and actually deliver on a decent overall experience.  The hope was that partner support would 📈 quickly for those.   Unfortunately, it didn't move as quickly as the platform and that generated confusion and frustration for folks trying to make use of them.   I do hope those return because easy access to this functionality is very much needed in many systems.

The listing at https://platform.pokitdok.com/documentation/v4/#available-api-endpoints should be up-to-date for available APIs.    I'll work up a PR to clean up these spots in the library to avoid any other confusion for folks in the future.    Thank you very much for reporting this issue!  

Thank you,

Brian
🚜💻

**Comment by kenpachiii** [comment]
Well that's unfortunate. I was hoping I stumbled upon unknown gold within the code, but seems the unremoved deprecated feature avails yet again! I appreciate the information you provided to clear things up and I hope one day for their return as well. 

On a different topic I have an additional question that I'm having difficulty finding clarity on in the documentation. But does the claims API end point work for both 837p and 837i transactions? My concern comes from not seeing any parameters related to fields like `revenue code` or `type of bill`. I do see that from `facility_type` the `type of bill` could be easily inferred. I'm just not seeing any other similar type of connection for `revenue code`.

**Comment by corbinbs** [comment]
Hi @kenpachiii 

I wish I could offer you that unknown gold today, too 🏅 🙌 
Really sorry about the mix up there.   

Technically the claims API does support both professional (X12 837P) and institutional (X12 837I) transactions.  (The ability to JSON<->X12 837I files)   If you were to include `admission_type` on a request, additional request validation would kick in to check for `admission_source`, `patient_status`, `facility_type`, and each `service_lines` item would be checked for a `revenue_code`.   It would also then tag that claim internally as an institutional claim instead of a professional claim.  However, the public/listed trading partner connections at https://dashboard.pokitdok.com/#/trading-partners only support professional claims today when submitted via the PokitDok Platform.    Part of that focus on professional claims connectivity came from the needs of early platform customers.   The new companies / developers that showed up first all wanted/needed a simple way to push professional style claims and wanted a similar feel to the eligibility API that was part of an early PokitDok marketplace product and was extracted based on customer feedback/requests.      I don't know when/if additional partner connections will be added to allow the current claims API to deliver institutional claims transactions to the desired partner(s). 

Sorry for striking out on all of the questions today but I hope this information helps you out as you're exploring the APIs and trying to navigate toward a solution for your specific needs.    

Thanks again,

Brian
🚜💻
